version: 2

seeds:
    - name: employees
      description: A manual map of employees to customers.
      columns:
        - name: employee_id
          description: The unique identifier of the employee.
          tests:
            - not_null  
            - unique
